argo-cd:  
  redis-ha:
    enabled: false
    
  ## Repo Server
  repoServer:      
    # -- The number of repo server pods to run
    replicas: 1

    autoscaling:
      # -- Enable Horizontal Pod Autoscaler ([HPA]) for the repo server
      enabled: false

    ## Repo server metrics service configuration
    metrics:
      # -- Deploy metrics service
      enabled: false   
      serviceMonitor:
        # -- Enable a prometheus ServiceMonitor
        enabled: false   

    env:   
      - name: AVP_K8S_MOUNT_PATH
        value: auth/sahab2/dev/security-dev      
      - name: AVP_K8S_ROLE
        value: security-dev  
      - name: VAULT_ADDR
        value: http://host.minikube.internal:8200 
      - name: AVP_TYPE
        value: vault  
      - name: AVP_AUTH_TYPE
        value: k8s  
      - name: VAULT_SKIP_VERIFY
        value: "1"    
        

  server:     
    # -- The number of server pods to run
    replicas: 1

    autoscaling:
      # -- Enable Horizontal Pod Autoscaler ([HPA]) for the Argo CD server
      enabled: false
      
    ## Server metrics service configuration
    metrics:
      # -- Deploy metrics service
      enabled: false

      serviceMonitor:
        # -- Enable a prometheus ServiceMonitor
        enabled: false   
