global:
  image:
    # -- If defined, a repository applied to all Argo CD deployments
    repository: kadirzade/argocd
    tag: "v2.3.4"
    
argo-cd:   
  # This key configures Redis-HA subchart and when enabled (redis-ha.enabled=true)
  # the custom redis deployment is omitted
  # Check the redis-ha chart for more properties
  redis-ha:
    # -- Enables the Redis HA subchart and disables the custom Redis single node deployment
    enabled: true
    exporter:
      # -- If `true`, the prometheus exporter sidecar is enabled
      enabled: true

  ## Server
  server:
    # -- The number of server pods to run
    replicas: 2

    autoscaling:
      # -- Enable Horizontal Pod Autoscaler ([HPA]) for the Argo CD server
      enabled: true
      # -- Minimum number of replicas for the Argo CD server [HPA]
      minReplicas: 2

    ## Server metrics service configuration
    metrics:
      # -- Deploy metrics service
      enabled: true

      serviceMonitor:
        # -- Enable a prometheus ServiceMonitor
        enabled: true

    # -- Manage Argo CD configmap (Declarative Setup)
    ## Ref: https://github.com/argoproj/argo-cd/blob/master/docs/operator-manual/argocd-cm.yaml
    configEnabled: true
    config:
      configManagementPlugins: |
        - name: argocd-vault-plugin-helm
          generate:
            command: ["bash", "-c"]
            args: ['helm template "$ARGOCD_APP_NAME" -f <(echo "$HELM_VALUES") . > all.yaml && argocd-vault-plugin generate all.yaml'] 

    additionalProjects: 
    - name: argocd
      namespace: argocd
      additionalLabels: {}
      additionalAnnotations: {}
      description: Argocd Project
      sourceRepos:
      - '*'
      destinations:
      - namespace: argocd
        server: https://kubernetes.default.svc
      clusterResourceWhitelist:
      - group: '*'
        kind: '*'
      orphanedResources:
        warn: false            

  ## Repo Server
  repoServer:

    # -- The number of repo server pods to run
    replicas: 2

    autoscaling:
      # -- Enable Horizontal Pod Autoscaler ([HPA]) for the repo server
      enabled: true
      # -- Minimum number of replicas for the repo server [HPA]
      minReplicas: 2    

    ## Repo server metrics service configuration
    metrics:
      # -- Deploy metrics service
      enabled: true   
      serviceMonitor:
        # -- Enable a prometheus ServiceMonitor
        enabled: true 

    ## Enable Admin ClusterRole resources.
    ## Enable if you would like to grant cluster rights to Argo CD repo server.
    clusterAdminAccess:
      # -- Enable RBAC for local cluster deployments
      enabled: true

    clusterRoleRules:
      # -- Enable custom rules for the Repo server's Cluster Role resource
      enabled: true
      # -- List of custom rules for the Repo server's Cluster Role resource
      rules: 
      - verbs:
          - create
        apiGroups:
          - authentication.k8s.io
        resources:
          - tokenreviews
      - verbs:
          - create
        apiGroups:
          - authorization.k8s.io
        resources:
          - subjectaccessreviews  

  # ## Argo Configs
  # configs:
  #   credentialTemplates: 
  #     github-ssh-creds:
  #      url: <url>
  #      sshPrivateKey: <sshPrivateKey>

  applicationSet:
    # -- Enable Application Set controller
    enabled: false